version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:realTimeChatPassword@db:5432/realTimeChat?schema=public"
      BCRYPT_SALT_ROUNDS: "10"
      JWT_SECRET: "secret_token"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: realTimeChatPassword
      POSTGRES_DB: realTimeChat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  pgdata:
